[profile.default]
via_ir = true
ffi = true
fs_permissions = [
    { access = "read", path = "./config.json" }
]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
